name: Danfoss Data Logger

on:
  repository_dispatch:
    types: [starte_logger]
  workflow_dispatch: # Erlaubt weiterhin den manuellen Button-Klick

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: R installieren
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Nötige R-Pakete installieren
        run: |
          Rscript -e 'install.packages(c("httr", "jsonlite", "dplyr", "tidyr", "lubridate"))'

      - name: Skript ausführen und Daten holen
        env:
          DANFOSS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DANFOSS_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: Rscript danfoss-logger.R

      - name: CSV committen und pushen
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add danfoss-logger.csv
          git commit -m "Automatisches Daten-Update" || echo "Keine neuen Daten"
          git pull --rebase
          git push
